### ISSUE TITLE
Some bugs that i found in ConsoleLogonHook

### ISSUE THREAD

**Issue by XdekTV** [wiktorwiktor12/ConsoleLogonHook#2] opened 2024-06-22 13:20 UTC
I was testing ConsoleLogonHook on a vm and decided to see, if there are any bugs (of course i know that this project is still in beta, but it's good to adress them)

Bug 1 - Shutdown button and the dropdown menu don't work (don't know if they are for now, deco only)
Bug 2 - Changing the password works, but displayes the "error" icon instead of the "information" icon and is missing the "Create a password reset disk or something like that"
Bug 3 - Multi Accounts are bugged and show wierd characteres
Bug 4 - Keyboard buttons are missing (i don't know if they can be brought back)
Bug 5 - When there is a single user on the computer and the pc is locked, it still shows the "Switch user" button
Bug 6 - When locked, it doesn't say if the user is logged in (again, don't know if it can be brought back)

These are the only ones that i could find (for now). Still, crazy that this is even possible.

**Comment by wiktorwiktor12** [comment] 2024-06-22 14:19
1. Deco only atm, will be added soon
2. aware
3. should be fixed in latest
4. will be added at a later date
5. aware, might take a bit of hacky tinkering to get this right
6. I know how to display the text, just need to investigate a way to check if the computer is locked

**Comment by XdekTV** [comment] 2024-06-22 17:14
> 1. Deco only atm, will be added soon
> 
>     2. aware
> 
>     3. should be fixed in latest
> 
>     4. will be added at a later date
> 
>     5. aware, might take a bit of hacky tinkering to get this right
> 
>     6. I know how to display the text, just need to investigate a way to check if the computer is locked

just tested ver. 1.0.2 and the names are still bugged. using a Windows 10 21H2 IoT Enterprise LTSC VM + Revert8Plus ver. 3.1 to test it

**Comment by XdekTV** [comment] 2024-06-22 17:14
idk how to use github lol, but just tested ver. 1.0.2 and the names are still bugged. using a Windows 10 21H2 IoT Enterprise LTSC VM + Revert8Plus ver. 3.1 to test it

**Comment by wiktorwiktor12** [comment] 2024-06-22 17:40
can you send a screenshot of it and a log file of it?
log file is stored in System32/Logs/CLH.log

**Comment by XdekTV** [comment] 2024-06-22 18:30
![obraz](https://github.com/wiktorwiktor12/ConsoleLogonHook/assets/134400911/4e991fdd-53f2-4a01-bc5c-6a0a4d6467e5)
The names of the users are: User, test. when clicking on any of those, i only get the account User. the account "test" is freshly created and has never been logged in. here is the log: 
[CLH.log](https://github.com/user-attachments/files/15937936/CLH.log)

**Comment by XdekTV** [comment] 2024-06-22 18:34
also when clicking "Switch user" in the CAD, it's acting 1:1 like the "Lock" option

**Comment by wiktorwiktor12** [comment] 2024-06-22 19:03
just looking at logs rn, i would recommend disabling the lock screen, this fixes a bug where u have to press ctrl alt delete to continue

**Comment by wiktorwiktor12** [comment] 2024-06-22 19:04
also try getting logs again, that log you sent doesn't seem to have you going into userselect

**Comment by XdekTV** [comment] 2024-06-22 19:18
> just looking at logs rn, i would recommend disabling the lock screen, this fixes a bug where u have to press ctrl alt delete to continue

i disabled it, or rather revert8plus did, but an update ruined it but i think it was the exact same

**Comment by XdekTV** [comment] 2024-06-22 19:24
> also try getting logs again, that log you sent doesn't seem to have you going into userselect

[CLH.log](https://github.com/user-attachments/files/15938089/CLH.log) - here is the log. i also made a quick vid to show what's happening if it doesn't show up in the log - https://youtu.be/exlB48tW2FY

**Comment by XdekTV** [comment] 2024-06-23 06:41
also i think you forgot to include ConsoleLogon.dll in ver. 1.0.3

**Comment by windowsxp3790** [comment] 2024-06-23 13:46
> also i think you forgot to include ConsoleLogon.dll in ver. 1.0.3

doesnt need it anymore

**Comment by XdekTV** [comment] 2024-06-23 13:55
> > also i think you forgot to include ConsoleLogon.dll in ver. 1.0.3
> 
> doesnt need it anymore

when i was trying to update from 1.0.2 and putting the files without any clh versions, it wouldn't let me just go to tge logon screen or CAD

**Comment by Erizur** [comment] 2024-06-25 21:49
> ![obraz](https://private-user-images.githubusercontent.com/134400911/341990728-4e991fdd-53f2-4a01-bc5c-6a0a4d6467e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTIyNzcsIm5iZiI6MTcxOTM1MTk3NywicGF0aCI6Ii8xMzQ0MDA5MTEvMzQxOTkwNzI4LTRlOTkxZmRkLTUzZjItNGEwMS1iYzVjLTZhMGE0ZDY0NjdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQyMTQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDQwMGQ4NDQ3YTA2Yjk2NmNiY2JiM2E2YmNiNGQ0N2Q3YjBiMjhhYjlkY2U1Yzc3MWI2NDE0NGVhYWI3MTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QNhJ87xk8UH7c4htGA5gDRkO9INyeWCBU9TJP07n46I) The names of the users are: User, test. when clicking on any of those, i only get the account User. the account "test" is freshly created and has never been logged in. here is the log: [CLH.log](https://github.com/user-attachments/files/15937936/CLH.log)

This seems to be caused by SecureUxTheme, when you have the option to Hook into LogonUI enabled. Try to disable it for now and test again.

**Comment by XdekTV** [comment] 2024-06-25 21:52
> > ![obraz](https://private-user-images.githubusercontent.com/134400911/341990728-4e991fdd-53f2-4a01-bc5c-6a0a4d6467e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTIyNzcsIm5iZiI6MTcxOTM1MTk3NywicGF0aCI6Ii8xMzQ0MDA5MTEvMzQxOTkwNzI4LTRlOTkxZmRkLTUzZjItNGEwMS1iYzVjLTZhMGE0ZDY0NjdlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQyMTQ2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDQwMGQ4NDQ3YTA2Yjk2NmNiY2JiM2E2YmNiNGQ0N2Q3YjBiMjhhYjlkY2U1Yzc3MWI2NDE0NGVhYWI3MTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QNhJ87xk8UH7c4htGA5gDRkO9INyeWCBU9TJP07n46I) The names of the users are: User, test. when clicking on any of those, i only get the account User. the account "test" is freshly created and has never been logged in. here is the log: [CLH.log](https://github.com/user-attachments/files/15937936/CLH.log)
> 
> This seems to be caused by SecureUxTheme, when you have the option to Hook into LogonUI enabled. Try to disable it for now and test again.

well, i'm using ultrauxthemepatcher (at least i think r8p uses that cause that's my testing vm). i will try tomorrow, cause it's basicly midnight for me

**Comment by MuntaserAlazzeh** [comment] 2024-06-26 17:00
there's a small problem the shutdown red button is not working even if i clicked it 100 times

**Comment by IPTVmanreal** [comment] 2024-06-26 18:41
It's currently only for decoration, future updates will make it functional

**Closed** 2024-06-30 18:43 UTC
